variables:
  HTTPS_PROXY: http://proxy.tcsbank.ru:8080
  HTTP_PROXY: http://proxy.tcsbank.ru:8080
  no_proxy: 'docker,.tinkoff.cloud,.tcsbank.ru,.tinkoff.ru'

stages:
  - test
  - build
  - deploy
  - finalize

include:
  - project: 'coretech-frontend/frontend-pipelines'
    file: '/microservices/jobs/auto-deploy-dynamic-on-branches.yml'
  - project: 'coretech-frontend/frontend-pipelines'
    file: '/microservices/jobs/auto-deploy-production-on-master.yml'
